### ISSUE TITLE
Внешний дисплей SSD1306 не работает

### ISSUE THREAD

**Issue by booroondook-eng** [vooon/elehant-to-mqtt#12]
Ввиду отсутствия у меня платы ESP32 с приклееным дисплеем, решил подключить внешний дисплей SSD1306 128x32.
Однако, он не работает. От слова "совсем". Просто черный экран.
Дисплей имеет адрес 0x3C.
Подключал так (слева дисплей, справа ESP32)
GND -> GND
VCC -> 3V3
SCL -> D22
SDA -> D21
Проверял на двух платах ESP32 - результат одинаковый
Сам дисплей проверялся на работоспособность, будучи подключенным к Arduino Uno с тестовым скетчем от Adafruit - дисплей рабочий.

**Comment by vooon** [comment]
https://github.com/vooon/elehant-to-mqtt/blob/01bcfe93ac9bd7aa6f616c938e46062826849292/src/config.h#L18-L21

Что-то я не уверен что D22/21 это 4/5.

**Comment by booroondook-eng** [comment]
Да, я тоже покопался в коде и выяснил, что 4 и 5. Но это уже переопределенные пины, а стандартные все-таки 22/21
![ESP32-36-Pin-Pinout](https://user-images.githubusercontent.com/8210458/215566277-05a8b6ef-cb37-459b-ae66-81d1be26378f.jpg)

**Comment by booroondook-eng** [comment]
Вдогонку. На 4/5 дисплей заработал, но бо́льшую часть времени показывает "NO DATA". Периодически на дисплее появляются показания, но через некоторое время (точно не засекал, но порядка минуты) снова заменяются на "NO DATA".
Нельзя ли сделать так, чтобы дисплей постоянно показывал последние полученные показания? Ну, и какой-нибудь индикатор, означающий, что эти показания устарели, а новых пока нет.
